# Do not double-build branches and PRs from this repo
if: repo != head_repo

_reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
_reference_os: &reference_os
  'linux'
git:
  depth: false
  autocrlf: input
os:
  - *reference_os
stages:
  - check
  - test
  - deploy
env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="DanySK/refreshversions-aliases"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
jobs:
  exclude:
    - os: *reference_os
      env: *reference_jdk
      stage: test
  include:
    - stage: check
      name: "Check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
    - stage: deploy
      name: "Deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_f778b2e1574b_key -iv $encrypted_f778b2e1574b_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - ./gradlew publish --stacktrace

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - travis_retry ./gradlew clean check
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    on_success: never # default: change
